### ISSUE TITLE
Adding TLorentzVectorArray

### ISSUE THREAD

**Issue by jeffkrupa** [scikit-hep/uproot3-methods#95]
Hi, I am defining two TLorentzVectorArray and wanting to take the sum. I can add `mu_p4` to itself, or `met_p4` to itself, but I cannot add them to each other without it blowing up. I'm using `awkward1` and `uproot_methods3`. What am I doing wrong?
```
>>> candidatemuon = ak.firsts(events.Muon)
>>> mu_p4 = TLorentzVectorArray.from_ptetaphim(ak.fill_none(candidatemuon.pt,0),ak.fill_none(candidatemuon.eta,0),ak.fill_none(candidatemuon.phi,0),ak.fill_none(candidatemuon.mass,0))
>>> met_p4 = TLorentzVectorArray.from_ptetaphim(ak.from_iter([[v] for v in events.MET.pt]),ak.from_iter( [[v] for v in np.zeros(len(events))]), ak.from_iter([[v] for v in events.MET.phi]), ak.from_iter([[v] for v in np.zeros(len(events))]) )
>>> mu_p4.shape, met_p4.shape
((100000,), (100000,))
>>> mu_p4 + met_p4
MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64
```

**Comment by jpivarski** [comment]
You can't use Awkward 1 with uproot-methods (any version). Lorentz vectors in the Awkward 1 era will be handled by the [Vector](https://github.com/scikit-hep/vector) package, which is going to get more fully developed in March, or by [coffea.nanoevents.methods.vector](https://coffeateam.github.io/coffea/modules/coffea.nanoevents.methods.vector.html) in the interim.

I'm guessing that what's happening here is that Awkward 0 doesn't recognize an Awkward 1 array and is iterating over it, or that some broadcasting rule applies and makes it want to generate a huge array (74.5 GiB).
